apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2020-07-29T20:53:06.291122116+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4a812e55a97339181fd90043cafd23752c8986e7591b32db5bb4dbfb53c63f35
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.9.tgz
    version: v0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2020-07-29T20:53:06.290299444+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: ce0ed4fc65c001750193ab83c470c40f245ee33c7e0884bbf0f48ecdb83ded0c
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.8.tgz
    version: v0.0.8
generated: "2020-07-29T20:53:06.289149332+03:00"
