apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2020-07-19T07:29:22.565386025+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9f65091ca30d5ecdeb2e178090837590667ddddcefdb77ed9e82df831c0d5891
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2020-07-19T07:29:22.564626871+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1db8d475eb4ac221be59191d6051503fa3ede24841f9d0580e5208f090f0a4b3
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-19T07:29:22.563964437+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e2a60b320d8caa3d2ee716ec97b3ebbe9685b75582589100ab47c037b54636d
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.1.tgz
    version: 0.0.1
  - apiVersion: v2
    appVersion: latest
    created: "2020-07-19T07:29:22.566146816+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: ae8a44f9a683144b65c1e9bc5aa1d2b2ba924c3ec228583e300b930aa0a1a29d
    name: kvdi
    type: application
    urls:
    - kvdi-latest.tgz
    version: latest
generated: "2020-07-19T07:29:22.563158794+03:00"
