apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.0.24
    created: "2020-09-03T08:20:41.475919071+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: dfe4cf0415b6c4fa641a363616a5dbddef741aa66705d354caec77bbcbe2e3c0
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.24.tgz
    version: v0.0.24
  - apiVersion: v2
    appVersion: v0.0.23
    created: "2020-09-03T08:20:41.475039839+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 8008d086d4adfd113e6fce84519d64801f989b6e7ccaa98b8fcf68a2eda6f616
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.23.tgz
    version: v0.0.23
  - apiVersion: v2
    appVersion: v0.0.22
    created: "2020-09-03T08:20:41.474053983+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e153630ce220c52777bb4bf1ac69a997141d907cd385444d947261ddbbb6df2
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.22.tgz
    version: v0.0.22
  - apiVersion: v2
    appVersion: v0.0.21
    created: "2020-09-03T08:20:41.473176974+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 266fb9d68a9f027f4274aacc302dc5d86273be0c3fe8f93f8d07a5ae3190c522
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.21.tgz
    version: v0.0.21
  - apiVersion: v2
    appVersion: v0.0.20
    created: "2020-09-03T08:20:41.471614705+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: a0228cb115992dd6332041d52fecea6d03c1bed004088fb3176e6c7e25f42e2b
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.20.tgz
    version: v0.0.20
  - apiVersion: v2
    appVersion: v0.0.19
    created: "2020-09-03T08:20:41.470639129+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 15da1226e9b81f0d090249a644e1d8d83d827fd180d47e576cf36e71b533a1e8
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.19.tgz
    version: v0.0.19
  - apiVersion: v2
    appVersion: v0.0.18
    created: "2020-09-03T08:20:41.469713544+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: a18c90ad5592dbb6e4d81ba2cadacdb75098fefd55e5a3bff88ec336e0669a4d
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.18.tgz
    version: v0.0.18
  - apiVersion: v2
    appVersion: v0.0.17
    created: "2020-09-03T08:20:41.468781919+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13a4993c221e1b95bfb45473981bd50e31f0f5f72ffddabf38e45f49be963e8c
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.17.tgz
    version: v0.0.17
  - apiVersion: v2
    appVersion: v0.0.16
    created: "2020-09-03T08:20:41.467875032+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 63ae78f0f336cf904ef14a1bf130e25a3842cfb4b51e23d283007a8756ef45c6
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.16.tgz
    version: v0.0.16
  - apiVersion: v2
    appVersion: v0.0.15
    created: "2020-09-03T08:20:41.466979543+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 291f5d5c7ce940833e87619413c0c145a303447cc3c2bb4fbfff04a2bb427ccd
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.15.tgz
    version: v0.0.15
  - apiVersion: v2
    appVersion: v0.0.14
    created: "2020-09-03T08:20:41.466138974+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 989009934d12576b05d3077eed3c2a6ceaad8ed4ed6c695a314682a2a1e47d4e
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.14.tgz
    version: v0.0.14
  - apiVersion: v2
    appVersion: v0.0.13
    created: "2020-09-03T08:20:41.465267183+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: dc573143ea29ffd3329b58e84633c5133101f0b8942c9211a206a8dc4ef88fc2
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.13.tgz
    version: v0.0.13
  - apiVersion: v2
    appVersion: v0.0.12
    created: "2020-09-03T08:20:41.464413134+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 7af2773b32835b8156a4f569b7374904c879243de043ac3609ce4575fe69c7e7
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.12.tgz
    version: v0.0.12
  - apiVersion: v2
    appVersion: v0.0.11
    created: "2020-09-03T08:20:41.463106225+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: bdfded943f784632068d5a7f8cf3767ae87a18aec4b3ec21845d19ccdb12c6ef
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.11.tgz
    version: v0.0.11
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2020-09-03T08:20:41.462279308+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 71acba01c305a02afe3237f89c32ca2e9d0048883e6c142e3c6138ff6b6eeb2e
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.10.tgz
    version: v0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2020-09-03T08:20:41.477448362+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4a812e55a97339181fd90043cafd23752c8986e7591b32db5bb4dbfb53c63f35
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.9.tgz
    version: v0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2020-09-03T08:20:41.476662311+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: ce0ed4fc65c001750193ab83c470c40f245ee33c7e0884bbf0f48ecdb83ded0c
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.8.tgz
    version: v0.0.8
generated: "2020-09-03T08:20:41.461351952+03:00"
