apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2021-02-10T22:08:12.049918+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 0ffcd67c8edb0e92e6ebc9963aec070468300c946809ea05679868bb53b17031
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.1.tgz
    version: v0.2.1
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2021-02-10T22:08:12.046277+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9160cb3d90f81dbfca51a32cae2fd05fa8402b645b276cf8387cb6ffe32ade63
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v2
    appVersion: v0.1.4
    created: "2021-02-10T22:08:12.0441709+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4dd6ffd2bb17689d042782056e7f90bb8bb1ad403a9dc4a9de340329f4d70322
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.4.tgz
    version: v0.1.4
  - apiVersion: v2
    appVersion: v0.1.3
    created: "2021-02-10T22:08:12.0424096+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: f2b9302e26762c49ed0ad53835b2c190e6c7d0722c8497f46f1c2080fd5b0576
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.3.tgz
    version: v0.1.3
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2021-02-10T22:08:12.0411384+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 369e83caa627379ba04bf79471da18e0ebca85ec527fc13729eb7bb733f502ef
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.2.tgz
    version: v0.1.2
  - apiVersion: v2
    appVersion: v0.1.1
    created: "2021-02-10T22:08:12.0394738+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13667a42c4be002e2980ca0625bb4a7399b171ee73a1f0fe1a3c4de7bdc377ba
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.1.tgz
    version: v0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-02-10T22:08:12.0381369+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 75b553c4fea1303767743944a8e470f6d56784b85f8a0698edc5e786fc3c05ac
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.0.tgz
    version: v0.1.0
generated: "2021-02-10T22:08:12.0364718+02:00"
