apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2020-07-25T09:50:00.392426386+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 96a853c926dfa5e12725cb8aa7f70fa128681bb61f76efd698a76365cd302948
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2020-07-25T09:50:00.391510705+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: b633203a861f307d2e7839330dc27de0cf509d28d0fa497e92ebf8436ece80f5
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2020-07-25T09:50:00.390698655+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9f65091ca30d5ecdeb2e178090837590667ddddcefdb77ed9e82df831c0d5891
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2020-07-25T09:50:00.389891555+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1db8d475eb4ac221be59191d6051503fa3ede24841f9d0580e5208f090f0a4b3
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-25T09:50:00.389151339+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e2a60b320d8caa3d2ee716ec97b3ebbe9685b75582589100ab47c037b54636d
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.1.tgz
    version: 0.0.1
  - apiVersion: v2
    appVersion: latest
    created: "2020-07-25T09:50:00.393316895+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: b6d3d0e5f01cb613e8d11cde456e067aa799535e96e1c5abe71e5b0f183d7163
    name: kvdi
    type: application
    urls:
    - kvdi-latest.tgz
    version: latest
generated: "2020-07-25T09:50:00.388236256+03:00"
