apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2020-07-25T17:10:53.300220837+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1a05c26678863e7125252233b8ecc64369592753672d4ec8d1d46b2ab49f9e7a
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2020-07-25T17:10:53.299392369+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 96a853c926dfa5e12725cb8aa7f70fa128681bb61f76efd698a76365cd302948
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2020-07-25T17:10:53.297470571+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: b633203a861f307d2e7839330dc27de0cf509d28d0fa497e92ebf8436ece80f5
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2020-07-25T17:10:53.296397363+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9f65091ca30d5ecdeb2e178090837590667ddddcefdb77ed9e82df831c0d5891
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2020-07-25T17:10:53.294170843+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1db8d475eb4ac221be59191d6051503fa3ede24841f9d0580e5208f090f0a4b3
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-25T17:10:53.293228673+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e2a60b320d8caa3d2ee716ec97b3ebbe9685b75582589100ab47c037b54636d
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.1.tgz
    version: 0.0.1
  - apiVersion: v2
    appVersion: latest
    created: "2020-07-25T17:10:53.301299495+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: b6d3d0e5f01cb613e8d11cde456e067aa799535e96e1c5abe71e5b0f183d7163
    name: kvdi
    type: application
    urls:
    - kvdi-latest.tgz
    version: latest
generated: "2020-07-25T17:10:53.291286288+03:00"
