apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2021-02-12T17:23:09.4036551+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 426e46b70297154030266abf2d832838c0d00c58a0b3390e78281400cea961fa
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.2.tgz
    version: v0.2.2
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2021-02-12T17:23:09.4018456+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 29af60d73698d30af6253b7d8317904a66f4de6378a16ac287d3c5905035be65
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.1.tgz
    version: v0.2.1
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2021-02-12T17:23:09.3999909+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: f50123e34bc62e2954da3ff2ae747f7d82c250cef5c53cf25d9dd163b542ef77
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v2
    appVersion: v0.1.4
    created: "2021-02-12T17:23:09.3973626+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4dd6ffd2bb17689d042782056e7f90bb8bb1ad403a9dc4a9de340329f4d70322
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.4.tgz
    version: v0.1.4
  - apiVersion: v2
    appVersion: v0.1.3
    created: "2021-02-12T17:23:09.3957222+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: f2b9302e26762c49ed0ad53835b2c190e6c7d0722c8497f46f1c2080fd5b0576
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.3.tgz
    version: v0.1.3
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2021-02-12T17:23:09.3945102+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 369e83caa627379ba04bf79471da18e0ebca85ec527fc13729eb7bb733f502ef
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.2.tgz
    version: v0.1.2
  - apiVersion: v2
    appVersion: v0.1.1
    created: "2021-02-12T17:23:09.39327+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13667a42c4be002e2980ca0625bb4a7399b171ee73a1f0fe1a3c4de7bdc377ba
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.1.tgz
    version: v0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-02-12T17:23:09.3919324+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 75b553c4fea1303767743944a8e470f6d56784b85f8a0698edc5e786fc3c05ac
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.0.tgz
    version: v0.1.0
generated: "2021-02-12T17:23:09.3889764+02:00"
