apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: 0.0.7
    created: "2020-07-27T13:27:25.724431821+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1f2bb2e94f8c38ea40ea7e440d7bdb41c40e392bdc7eb95c74e7ce9e45f8811d
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2020-07-27T13:27:25.723582669+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1a05c26678863e7125252233b8ecc64369592753672d4ec8d1d46b2ab49f9e7a
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2020-07-27T13:27:25.722411216+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 96a853c926dfa5e12725cb8aa7f70fa128681bb61f76efd698a76365cd302948
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2020-07-27T13:27:25.721553689+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: b633203a861f307d2e7839330dc27de0cf509d28d0fa497e92ebf8436ece80f5
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2020-07-27T13:27:25.720328384+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9f65091ca30d5ecdeb2e178090837590667ddddcefdb77ed9e82df831c0d5891
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2020-07-27T13:27:25.71920413+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1db8d475eb4ac221be59191d6051503fa3ede24841f9d0580e5208f090f0a4b3
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-07-27T13:27:25.718409379+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e2a60b320d8caa3d2ee716ec97b3ebbe9685b75582589100ab47c037b54636d
    name: kvdi
    type: application
    urls:
    - kvdi-0.0.1.tgz
    version: 0.0.1
generated: "2020-07-27T13:27:25.71752692+03:00"
