issues:
  exclude-rules:
  - path: pkg/api
    linters:
    - deadcode
    - unused
    - staticcheck
  - path: _test\.go
    linters:
      - errcheck
      - staticcheck
      - deadcode
      - unused
