apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: ubuntu-lxde
spec:
  image: quay.io/tinyzimmer/kvdi:ubuntu-lxde-0.0.1
  imagePullPolicy: IfNotPresent
  config:
    enableSound: false
    allowRoot: true
  tags:
    os: ubuntu
    desktop: lxde
    applications: minimal

---
apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: arch-xfce
spec:
  image: quay.io/tinyzimmer/kvdi:arch-xfce-0.0.1
  imagePullPolicy: IfNotPresent
  config:
    enableSound: true
    allowRoot: true
    init: systemd
  tags:
    os: archlinux
    desktop: xfce4
    applications: minimal
