apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  desktop:
    image: ghcr.io/tinyzimmer/kvdi:ubuntu-xfce4-latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    allowFileTransfer: true
  dind: 
    image: "docker:19-dind" # Defaults to latest which may have issues depending on your runtime
  tags:
    os: ubuntu
    desktop: xfce4
    applications: minimal

---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: dosbox
spec:
  desktop:
    image: ghcr.io/tinyzimmer/kvdi:dosbox-latest
    imagePullPolicy: IfNotPresent
    init: supervisord
  proxy:
    pulseServer: unix:///var/run/kvdi/pulse-server
  tags:
    os: ubuntu
    desktop: dosbox