apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: lxde-minimal
spec:
  image: quay.io/tinyzimmer/kvdi:lxde-0.0.1
  imagePullPolicy: IfNotPresent
  config:
    enableSound: false
    allowRoot: true
  tags:
    os: ubuntu
    desktop: lxde
    applications: minimal
---
apiVersion: kvdi.io/v1alpha1
kind: DesktopTemplate
metadata:
  name: kde-full
spec:
  image: quay.io/tinyzimmer/kvdi:kubuntu-desktop-0.0.1
  imagePullPolicy: IfNotPresent
  config:
    enableSound: true
    allowRoot: false
  tags:
    os: ubuntu
    desktop: kde
    applications: full
