# permissions for end users to view sessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: session-viewer-role
rules:
- apiGroups:
  - desktops.kvdi.io
  resources:
  - sessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - desktops.kvdi.io
  resources:
  - sessions/status
  verbs:
  - get
