# permissions for end users to edit vdiclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vdicluster-editor-role
rules:
- apiGroups:
  - app.kvdi.io
  resources:
  - vdiclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kvdi.io
  resources:
  - vdiclusters/status
  verbs:
  - get
