# permissions for end users to view vdiclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vdicluster-viewer-role
rules:
- apiGroups:
  - app.kvdi.io
  resources:
  - vdiclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kvdi.io
  resources:
  - vdiclusters/status
  verbs:
  - get
