---
apiVersion: v1
kind: Secret
metadata:
  name: kvdi-app-secrets
data:
  oidc-clientid: a3ZkaQ==
  oidc-clientsecret: WlhoaGJYQnNaUzFoY0hBdGMyVmpjbVYw
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNVENDQXhtZ0F3SUJBZ0lVVUVRT3p1eDFSdmZqZ3BzQVlxRW5IV2pTSDY4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RaR1Y0TG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTgpNakF3TnpFNE1USTFOVFF5V2hjTk5EVXdNekE1TVRJMU5UUXlXakFvTVNZd0pBWURWUVFEREIxa1pYZ3VaR1ZtCllYVnNkQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiRENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0MKQWdvQ2dnSUJBTjNXb2xTb1M2ak5YbXJKMVRKdFFLYkxlRWo2TXZNaC9ONk9XR0ZvdlBzdDVOeEZvYjhQQkFhaQphTGdjLzZ5THdZOFNOUlhWYUdGQnVRWUNuQmZEMmRaUzBnSStaZnQzQ1hnNEFneGp6ZzhHQ016cHV5WHdLdWpHClhjdldlNy9KY202ajh5WFBlSjV4NnFqby96b0s5c0JjeFpmQTBDNDk0V2pvU3lRWk1QMnphNFIrZ1dzRjFBQ1YKdU85ZmpVbTJYeWdMa2NVd2R5RUJNd3FJdlM1WG4zalQ4amVheHBnZU9EdzAzUnNWS05Obks0dmdGTEg5YjJhcQpvMXFWaE9XV1Bqbmd5RExnQ1UrdlJNdStsNVlMdXVHaWV3aWE3TzY5eG5IcHlQT25tZnRMeUM5K2FCa21yQlFICktLUVArV3lLZGhnY0JuOEk5Sm56OFVsMFJHaFYrcWhoOHlZa2kyeXdtY1Z0SDZHb2VQRVgxcGdwcU5Ob2VlbG8KY3JHdlVpOG9WaXg2ZVY4cGxQdU1QUWdFbUY4bHR1VEhvY0lzVHNYeVBsREpBZ3kyQlJnMGl3dFFaL2V1RlI1UgpJVmdMWWwyMmhReGNVK1NXWEprKzB4aDZ3cUg5UFhwUkVmZXdRb2Y0NS9vdk9yZVJlNGJzemczNHIvZWFrRGpaCjA3d29wZ2g5aHdXL1M2Y0lqeTFMQUpyQWVFbXFWZVowSW1CSERPOUNOb3lQSUY5eVNyLzRpMHZEc01ja0xNM0MKNGNJYkRRVC9Mc0duc3l6aUhMZDcwL1pRdzlrdUtvZG9JSGQ1TjVFZ3F2eGFsa2hNdUZHdVNVVStFb25pTnpiSQpUV3Q0blR1UGRNSGlOY2pjMXNKSTE2RmU2Z0hiZVNIN1lwbGFSRVdvaHJFalFqczkwRk9EQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCU0V4V3plcUxseUtPdzBnY0pESEwzbVpoNUNNekFmQmdOVkhTTUVHREFXZ0JTRXhXemUKcUxseUtPdzBnY0pESEwzbVpoNUNNekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElDQVFDMW5jNGhVeFF6NjBhMGZuM3IxQms4amp0V1BpSmRidFdIMkNBWEtDSW41RUFtTHRtNzVHTEdVOW9UCkRtUzRybDNYU3Z2WkZSUzZsSHRWc3hyLzQzWDBtd3FXQ0hYamxxMDdiV2k4VHU5NUQvOFRyQW9qL29hTTBYQ1QKUCtaaG9pK25sS0pNWjBaM0dva0ZIcmZ5eXhFYWpkUVVIUDBLZUVlbVFOZ2E5endFT0FZN3FTcXJxMTh0SlEzawo5YkdYMTZmVEdoWHQvSk92bTY2dk1kVlh3QjE3UEJlQUhpdGxSY2VudzJLekhHZGNIUS93T2FSR2V1UUw2NnFMCkh5eHQvYzNZZTQvc3RpSUo5YVlIR2Y3RHUrREh1dlQvVDdvc0o2REFlaGVuZVZGS0I4YmdEZUdCWVYzdTFQRjEKZ1k2WS9aRHl5b1pIVFErQS9BUm56cjExY2RDQVhCeFpQZlZLa0NZMWZRUW55WUxLaVdRMWR1TFZOUnRYMlRXTApVMDBjQmFnK1BnY0NnWXlwcFZmWGdVNkdaa3Z6cFY5cktXOEM3RnUrZ3NLbWVIL0NmUUk2WlJnK3JVQzJNZlJJCkIrQ2gxNGgwM080VjVveDRmaUs3WFdxQW92YUEyaFlnR0lUanAzcGs0WmxkTWQySHNReWFlcEFxUHh0cml4MzEKMGxSeHdia3BSNE9XaXhEd1RMSk1ZaXp0dE5zVWw0dWtvcHdxaWExU1ZQSWxpMFNpb2VBbWtxZjQvQWMwano5dQo2T0YxaU9ZeUVVV2FrYmVwb3h4U2VSU3ZSeFBBZHpLWDZ4MGZ0ekk2a3BJWHFoUnZ4Vmg2dEtwRTU3bG9KS0JsCmFSaWRIdVZ4MS9TaURmc0puVXV1WFlZQ25ZMFdnOWNqUGxuYWhsamFJdGpkVzc3eUZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBM2RhaVZLaExxTTFlYXNuVk1tMUFwc3Q0U1BveTh5SDgzbzVZWVdpOCt5M2szRVdoCnZ3OEVCcUpvdUJ6L3JJdkJqeEkxRmRWb1lVRzVCZ0tjRjhQWjFsTFNBajVsKzNjSmVEZ0NER1BPRHdZSXpPbTcKSmZBcTZNWmR5OVo3djhseWJxUHpKYzk0bm5IcXFPai9PZ3Iyd0Z6Rmw4RFFMajNoYU9oTEpCa3cvYk5yaEg2Qgphd1hVQUpXNDcxK05TYlpmS0F1UnhUQjNJUUV6Q29pOUxsZWZlTlB5TjVyR21CNDRQRFRkR3hVbzAyY3JpK0FVCnNmMXZacXFqV3BXRTVaWStPZURJTXVBSlQ2OUV5NzZYbGd1NjRhSjdDSnJzN3IzR2Nlbkk4NmVaKzB2SUwzNW8KR1Nhc0ZBY29wQS81YklwMkdCd0dmd2owbWZQeFNYUkVhRlg2cUdIekppU0xiTENaeFcwZm9haDQ4UmZXbUNtbwowMmg1NldoeXNhOVNMeWhXTEhwNVh5bVUrNHc5Q0FTWVh5VzI1TWVod2l4T3hmSStVTWtDRExZRkdEU0xDMUJuCjk2NFZIbEVoV0F0aVhiYUZERnhUNUpaY21UN1RHSHJDb2YwOWVsRVI5N0JDaC9qbitpODZ0NUY3aHV6T0RmaXYKOTVxUU9OblR2Q2ltQ0gySEJiOUxwd2lQTFVzQW1zQjRTYXBWNW5RaVlFY003MEkyakk4Z1gzSkt2L2lMUzhPdwp4eVFzemNMaHdoc05CUDh1d2FlekxPSWN0M3ZUOWxERDJTNHFoMmdnZDNrM2tTQ3EvRnFXU0V5NFVhNUpSVDRTCmllSTNOc2hOYTNpZE80OTB3ZUkxeU56V3dralhvVjdxQWR0NUlmdGltVnBFUmFpR3NTTkNPejNRVTRNQ0F3RUEKQVFLQ0FnRUFxdU50ZDFPUnZQNC9Mbm8rWHJNa3E1aHdGNStOWWhnYmlJSVUrU3pLNzU5aC9vRXhZVkc2NHpWMgovK1Z1MjBkcG1zSUczTVBodlpINGF2WFZzc1R2YVJleHFZTFI0czNISUxIY2VoamtJbFNlc09PWWhGZ25aZHR4Clk5WGN6RmZ0YStlbUpjbFYvSkI2bVJXcmp0WGxVVGZtQ3NuQVZPN2NWb2tqWVRKNnQrVGYvVmZLY0Z3ei9TTloKTENUcVhRODg3RWRGU3FiVURqdXpTdmtjNnJjYkpPUDRZZmM3NXZEWWx5Q045dy9zdkRWc3FUcThGb1RKclVmagp3S01QbGlDUDNOd1l2SUF6REF4VExiU3JaeTJ3RDZLdnJtaFIvbk40akVYd3hDbW5CNXRRSWEzNW1PNWVmcXNwCkZvRXJ2ZjVIakxrQ0ZCZ2MvUCtiTHQ5KzF2VHN1aHZqSk5mV3YvM2UxZ3lzYmw5RkM4WjVTYWtadjd1QVZsZFYKVkp5V1AzcVBPUEwzZHZjaS9vdFhEMnU2ZjRJWi9IZ0lIZGFGN2ZNNjNMMVhuVk9nUEZpMlRzUlZsUnM0NUIzKwp4N0hwM0pmMUN4cDYwRXNzM0lIdEpGZ1pDYnN4SDQ3bnhrWURWTXErdnN6VUlHcjlJN0gvZDVyTXU4b2tGYWpJCmhlWmFhRzN1MjU1L3U1anZjTExXY3hoc0dGN2JYbUJsZEZOREpLSmdackNQVGJUUUgwZ0xHQmNvbW9LSjlhb3QKSTlQTm5KdVl6ZG9rR014cDBsUzI1RkhXMEMzcnBhZlRndGdrNGUySnBWZ3lCaEdlZEd0Qm1TRVpsekN1ZUwzaApHdU9WRi9xemQyK00xN1NaUlNKZGsraHJuSEFvSzFja2daNEY1SVlhNGE0czdhZk0wb2tDZ2dFQkFQcWRLbjdDClp6Ymk3YmtNVW0vanpTV00vckQvUDhNbk5sQmZnNSt3S25ZZGpkVWdzaE51RjV5ZjV4d01Mazl5NWgxQ2hYakgKWVdUTFNUNUNVZ0pqVHRqSll6TXVEdGplSm1IZERBL3VmMXdFQVBUUHRvOWZyeEdWWGkxWHVCakQwRVR2azRpVwpwK2F2Tm1FLzU5OVJRMEpjNGRhb3ozRDlkM1A3ZTRPdDJrd2xqWTZCNXI5M1QzZkdyQlFWTkhOR3ZOSkZuZWYwCjZZVWtwRDF4SDd6UEIxZVUvVU5OeEhMblErUDQ0NkxSenBxRGIzMWVsYTlDSGh5YXFTenJDZWdBdHdzc0JPUmgKWVpuQUlpYnpGbnRQWmtGNnBNNnUxdWZuU2JFS3QzcEZKQ282dHRuNVRhd3RmN0Y2UG9WYVVpNndHUHJpeHpoNApOenNTUkwvVW1ZQWJSbTBDZ2dFQkFPS2JKbmN6cFcrbzRNTXJOb211Mi81NDYyM053TFYyalJDS2xuUk44RmtWCk5uUjJMdnVGTEhKcGowRmpnRmx2VlFiRTkrcmpYQmFxbnZYamExdUNMM1dpZEJ3V3JOM09BRDIvajBpYmRzY3MKWnZodmZmVmxnY2VuZTdaUGZ5S3ZTaE81UWRUcTc5aVpiK2tBb2FDRldsb1cwcG51UVphTS9hOTJQWWxncW1maQpyUlBOTVpibVM4eXJRcUJjK1QxWkxoc2QwYmVZOFh1cjV4WktTRlZ5c2RhTnZGUTNhZEVlZU5PNWM2c2hRTDNnCndVSExHSWcva2dnaTlZc0lQejB0d1k4YXQvdDNXeU9TZXBPK0k3cGdKRkRoMEEwMGFFSUtZMDlkWkZmQXRhVjYKQzlRRlMxUmEwT1UxVTBoUGJmcUp2bXM1dVI2OTY5V2dwRmd5eVM3bWk2OENnZ0VBSHh1NU5hamQ5UU13TFFNcApqSGdEZEFEUGNKc09pQ1BxNndrZ0pvZFFqZjdYSnpoNndreXRJNlQ1cEJLakFQdXJNc0NhSHNicEFRRDI0NEtKCitYL29QcUtvN0tadjgxMkgrQ2ZmSW04aFlnT2hOc0k5MEFnNWkvNDFoWDFZL2NINHJVWHIwMDJZSTl0bDdhWm8KR3VGVWJ2MW1qeVcvTWpCVVRwSk4zNmVKN0YvUTlYcU1jUUhYWEcvTjFtUlhjV083ZG9KcnVtbzlQbWl3OW10LwpYQWw2eU5WV3BxOFZqb25FZEp6bGJNV01Wc092NkNrQWZaUEFkeDUvbDNMSmRRSDV0cXBOSlNndFhFOXNMZGVJCjE5K2dPc3FGZ0o1VlVNMzE2TU1DeVd1aHRKZzdNRTF3NWNsMEMweTRUQWROSWp4N3JWRFBGK1JjUHJuaXpNa1EKRU1YUjlRS0NBUUJNY1VJOG0vT0hBMVV2QVhqWVlXQmRLN1ZmeVRUbEFpVDhHNFE5bjcwZ2tBTmFyak9UTFkyYwoydmMwZTdoa2N5WWZybnBqaG1jZVRsaHBZbHBvK0RYQ1hSY0dFckFsOHNRcUVHRHBnV2hFTURwY1BHQWxWQ1MvCmtVUXVjQXJYVElLVXZMMzBjWHlQZU5ORHFxN2JVNkR6R3hmWVRZTmFvaDFCLzRVcXZxMDlkajRrbStmS204MmUKTVhlOFdTRExEVFo4ZDBhenhLaFJxOSs4cVRwVmVPZDlGVHNldmNLNGhLc0Y0VjJmc1F3Q0FidXYwaTlvWnVtQQpUU3EveC94dFN1NHN0RHEwWGNNazhOamcxaGQvVzhka2NZaVpxOEF2NXdreFVMUDAxbEZ3alFkSWNyREN1QkFZCkFqRWlCNGwySnRsUm1wdFVQNFU2LzRIeEx0Q25QYWFKQW9JQkFRRHpwOGpxMHUzdXVXRUVMWGJqMXl5WTJ5TSsKM0VIN2tUTld2MVJDcm1TclFKVGtXSmVpKzB4bTYzN2pjV0pGMk9meC9rUGhxWGpVMk9HaEs3UTJWeG1McDNMRwp3bUdFK3U5bjk5YU1pR0kvaW95UkZpRmtJdWNqcnQxTUNrNEp3OXVnZEVmbCtOeDJkdFRBNCswS3A0dC80OXZMCk5KajZETTF1K3B1QW9EbHRNN1c3NW1BKzdxa09pY2xYaVBUenJlQ0Ywbnlaai9qU25seDkzNk1oMDdzUFhqMkgKdHlIUGptQ0ZNVm96V3E4V05nS0dVdmtOUkJZUmRMMEFjQTFUOUZFZnlaK2FEdkhQZ1V2REp1SXFkUHAwYjBVUApOOXB2aUlWdEJ2dE1GZS8yYXlLQzJZU0VLVk9lcTRLbWoraGszYmczMTlmNGE0OXJSYk9JZGRnalB2THMKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNVENDQXhtZ0F3SUJBZ0lVVUVRT3p1eDFSdmZqZ3BzQVlxRW5IV2pTSDY4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RaR1Y0TG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTgpNakF3TnpFNE1USTFOVFF5V2hjTk5EVXdNekE1TVRJMU5UUXlXakFvTVNZd0pBWURWUVFEREIxa1pYZ3VaR1ZtCllYVnNkQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiRENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0MKQWdvQ2dnSUJBTjNXb2xTb1M2ak5YbXJKMVRKdFFLYkxlRWo2TXZNaC9ONk9XR0ZvdlBzdDVOeEZvYjhQQkFhaQphTGdjLzZ5THdZOFNOUlhWYUdGQnVRWUNuQmZEMmRaUzBnSStaZnQzQ1hnNEFneGp6ZzhHQ016cHV5WHdLdWpHClhjdldlNy9KY202ajh5WFBlSjV4NnFqby96b0s5c0JjeFpmQTBDNDk0V2pvU3lRWk1QMnphNFIrZ1dzRjFBQ1YKdU85ZmpVbTJYeWdMa2NVd2R5RUJNd3FJdlM1WG4zalQ4amVheHBnZU9EdzAzUnNWS05Obks0dmdGTEg5YjJhcQpvMXFWaE9XV1Bqbmd5RExnQ1UrdlJNdStsNVlMdXVHaWV3aWE3TzY5eG5IcHlQT25tZnRMeUM5K2FCa21yQlFICktLUVArV3lLZGhnY0JuOEk5Sm56OFVsMFJHaFYrcWhoOHlZa2kyeXdtY1Z0SDZHb2VQRVgxcGdwcU5Ob2VlbG8KY3JHdlVpOG9WaXg2ZVY4cGxQdU1QUWdFbUY4bHR1VEhvY0lzVHNYeVBsREpBZ3kyQlJnMGl3dFFaL2V1RlI1UgpJVmdMWWwyMmhReGNVK1NXWEprKzB4aDZ3cUg5UFhwUkVmZXdRb2Y0NS9vdk9yZVJlNGJzemczNHIvZWFrRGpaCjA3d29wZ2g5aHdXL1M2Y0lqeTFMQUpyQWVFbXFWZVowSW1CSERPOUNOb3lQSUY5eVNyLzRpMHZEc01ja0xNM0MKNGNJYkRRVC9Mc0duc3l6aUhMZDcwL1pRdzlrdUtvZG9JSGQ1TjVFZ3F2eGFsa2hNdUZHdVNVVStFb25pTnpiSQpUV3Q0blR1UGRNSGlOY2pjMXNKSTE2RmU2Z0hiZVNIN1lwbGFSRVdvaHJFalFqczkwRk9EQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCU0V4V3plcUxseUtPdzBnY0pESEwzbVpoNUNNekFmQmdOVkhTTUVHREFXZ0JTRXhXemUKcUxseUtPdzBnY0pESEwzbVpoNUNNekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElDQVFDMW5jNGhVeFF6NjBhMGZuM3IxQms4amp0V1BpSmRidFdIMkNBWEtDSW41RUFtTHRtNzVHTEdVOW9UCkRtUzRybDNYU3Z2WkZSUzZsSHRWc3hyLzQzWDBtd3FXQ0hYamxxMDdiV2k4VHU5NUQvOFRyQW9qL29hTTBYQ1QKUCtaaG9pK25sS0pNWjBaM0dva0ZIcmZ5eXhFYWpkUVVIUDBLZUVlbVFOZ2E5endFT0FZN3FTcXJxMTh0SlEzawo5YkdYMTZmVEdoWHQvSk92bTY2dk1kVlh3QjE3UEJlQUhpdGxSY2VudzJLekhHZGNIUS93T2FSR2V1UUw2NnFMCkh5eHQvYzNZZTQvc3RpSUo5YVlIR2Y3RHUrREh1dlQvVDdvc0o2REFlaGVuZVZGS0I4YmdEZUdCWVYzdTFQRjEKZ1k2WS9aRHl5b1pIVFErQS9BUm56cjExY2RDQVhCeFpQZlZLa0NZMWZRUW55WUxLaVdRMWR1TFZOUnRYMlRXTApVMDBjQmFnK1BnY0NnWXlwcFZmWGdVNkdaa3Z6cFY5cktXOEM3RnUrZ3NLbWVIL0NmUUk2WlJnK3JVQzJNZlJJCkIrQ2gxNGgwM080VjVveDRmaUs3WFdxQW92YUEyaFlnR0lUanAzcGs0WmxkTWQySHNReWFlcEFxUHh0cml4MzEKMGxSeHdia3BSNE9XaXhEd1RMSk1ZaXp0dE5zVWw0dWtvcHdxaWExU1ZQSWxpMFNpb2VBbWtxZjQvQWMwano5dQo2T0YxaU9ZeUVVV2FrYmVwb3h4U2VSU3ZSeFBBZHpLWDZ4MGZ0ekk2a3BJWHFoUnZ4Vmg2dEtwRTU3bG9KS0JsCmFSaWRIdVZ4MS9TaURmc0puVXV1WFlZQ25ZMFdnOWNqUGxuYWhsamFJdGpkVzc3eUZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
data:
  config.yaml: |
    issuer: https://dex.default.svc.cluster.local:5556
    storage:
      type: sqlite3
      config:
        file: /db/dex.db
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/tls/tls.crt
      tlsKey: /etc/tls/tls.key
    logger:
      level: "debug"
      format: "text"
    staticClients:
    - id: kvdi
      redirectURIs:
      - 'https://kvdi.local/api/login'
      name: 'kVDI'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: mockCallback
      id: mock
      name: Example
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@kvdi.io"
      # bcrypt hash of the string "password"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - name: dex
        image: quay.io/dexidp/dex:v2.24.0
        ports:
        - name: web
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: tls
          mountPath: /etc/tls
        - name: db
          mountPath: /db
        command: ["dex", "serve", "/app/config/config.yaml"]
      volumes:
      - name: config
        configMap:
          name: dex-config
      - name: tls
        secret:
          secretName: dex-tls
      - name: db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  selector:
    app: dex
  ports:
  - name: web
    protocol: TCP
    port: 5556
    targetPort: 5556
