apiVersion: kvdi.io/v1alpha1
kind: VDIRole
metadata:
  name: kvdi-oidc-users
  annotations:
    kvdi.io/oidc-groups: authors
  labels:
    kvdi.io/cluster-ref: kvdi
rules:
- namespaces:
  - '*'
  resourcePatterns:
  - .*
  resources:
  - templates
  verbs:
  - read
  - use
  - launch
