apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: desktops.kvdi.io
spec:
  group: kvdi.io
  names:
    kind: Desktop
    listKind: DesktopList
    plural: desktops
    singular: desktop
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Desktop is the Schema for the desktops API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DesktopSpec defines the desired state of Desktop
          properties:
            template:
              description: The DesktopTemplate for booting this instance.
              type: string
            user:
              description: The username to use inside the instance, defaults to `anonymous`.
              type: string
            vdiCluster:
              description: The VDICluster this Desktop belongs to. This helps to determine
                which app instance certificates need to be created for.
              type: string
          required:
          - template
          - vdiCluster
          type: object
        status:
          description: DesktopStatus defines the observed state of Desktop
          properties:
            running:
              description: Whether the instance is running and resolvable within the
                cluster.
              type: boolean
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
