apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kvdi.fullname" . }}-app
rules:
- apiGroups:
  - kvdi.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
