apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kvdi.fullname" . }}-manager
  labels:
    {{- include "kvdi.labels" . | nindent 4 }}
    component: kvdi-manager
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "kvdi.selectorLabels" . | nindent 6 }}
      component: kvdi-manager
  template:
    metadata:
      labels:
        {{- include "kvdi.selectorLabels" . | nindent 8 }}
        component: kvdi-manager
    spec:
    {{- with .Values.manager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kvdi.serviceAccountName" . }}-manager
      securityContext:
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-manager
          securityContext:
            {{- toYaml .Values.manager.securityContext | nindent 12 }}
          image: "{{ .Values.manager.image.repository }}:{{ include "kvdi.managerTag" . }}"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kvdi"
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
