{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kvdi.serviceAccountName" . }}-manager
  labels:
{{ include "kvdi.labels" . | nindent 4 }}
{{- end -}}
