apiVersion: kvdi.io/v1alpha1
kind: VDICluster
metadata:
  name: kvdi
  labels:
    {{- include "kvdi.labels" . | nindent 4 }}
    component: kvdi-cluster
spec:
  {{ toYaml .Values.vdi.spec | nindent 2 }}
