name: Build

on:
  create:
    tags:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Login to container reigstry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u tinyzimmer --password-stdin

    - name: Get image version
      shell: bash
      run: |
        echo ::set-output name=tag::$([[ "${GITHUB_REF##*/}" == "main" ]] && echo latest || echo ${GITHUB_REF##*/})
      id: version

    - name: Build the manager docker image
      run: VERSION=${{ steps.version.outputs.tag }} make generate build-manager

    - name: Build the app docker image
      run: VERSION=${{ steps.version.outputs.tag }} make build-app

    - name: Build the kvdi-proxy docker image
      run: VERSION=${{ steps.version.outputs.tag }} make build-kvdi-proxy

    - name: Push the manager docker image
      run: VERSION=${{ steps.version.outputs.tag }} make push-manager
      if: ${{ github.event_name != 'pull_request' }}

    - name: Push the app docker image
      run: VERSION=${{ steps.version.outputs.tag }} make push-app
      if: ${{ github.event_name != 'pull_request' }}

    - name: Push the kvdi-proxy docker image
      run: VERSION=${{ steps.version.outputs.tag }} make push-kvdi-proxy
      if: ${{ github.event_name != 'pull_request' }}

    - name: Force pkg.go.dev to refresh main
      run: curl "https://proxy.golang.org/github.com/tinyzimmer/kvdi/@v/${GITHUB_REF##*/}.info"
      if: ${{ steps.version.outputs.tag == 'latest' && github.event_name != 'pull_request' }}

    - name: Force pkg.go.dev to refresh version
      run: curl https://proxy.golang.org/github.com/tinyzimmer/kvdi/@v/${{ steps.version.outputs.tag }}.info
      if: ${{ steps.version.outputs.tag != 'latest' && github.event_name != 'pull_request' }}
